dell-asm/dell-asm-util

- dell-asm-util.gemspec
Needs to be able to support both asm-deployer and razor-server which
request different versions of some gems such as hashie.
> ASM-1973 relax dell-asm-util version requirements

- lib/asm/wsman.rb
ASM::WsMan.reboot was moved into dell-asm-util, but included a
static file reboot.xml as part of its arguments. The reboot.xml
was not moved into dell-asm-util causing that function to
fail. The reboot.xml file was not really needed since the
RebootJobType parameter it provided was already included as a
wsman property, so this fix just removed its use.
> ASM-4913 fix ASM::WsMan.reboot from gem refactor

- lib/asm/network_configuration.rb
- spec/fixtures/network_configuration/blade_fc.json
- spec/fixtures/network_configuration/blade_partitioned.json
- spec/fixtures/network_configuration/blade_unpartitioned.json
- spec/fixtures/network_configuration/rack_partitioned.json
- spec/unit/asm/network_configuration_spec.rb
Still some changes that need to be made later once the switch/blade code has been properly refactored.  There's some code in the switch configuration methods that still relies on the "is_blade?" method that should go away, but since it's being refactored already, there's not much point to redo that code ATM.
> ASM-4853 Partial support for new UI network config model

- .gitignore
- lib/asm/wsman.rb
- spec/unit/asm/wsman_spec.rb
In ASM::WsMan.boot_to_network_iso, need to detach ISO before checking
LC ready. LC will always show as "not ready" if an ISO is currently
attached.
> ASM-2058 detach ISO before checking LC ready

- lib/asm/network_configuration.rb
- spec/unit/asm/network_configuration_spec.rb
The ipRange field contains a list of ip ranges associated with the
given network. It is sometimes passed in different orders, which can
cause networkObjects that are ostensibly same (the same network id and
same static IP if it is a static network) to appear different. That
causes difficulty when doing things like trying to determine the set
of networks that are being used on a port.
> remove ipRange from networkObjects in network_configuration

- lib/asm/network_configuration.rb
- lib/asm/network_configuration/nic_info.rb
- lib/asm/network_configuration/nic_port.rb
- lib/asm/network_configuration/nic_type.rb
- lib/asm/network_configuration/nic_view.rb
- lib/asm/wsman.rb
- spec/unit/asm/network_configuration/nic_info_spec.rb
- spec/unit/asm/network_configuration/nic_port_spec.rb
- spec/unit/asm/network_configuration_spec.rb
Previously server NICs were assigned to NetworkConfiguration
interfaces solely based on NIC order. I.e. if the user chose a 4x10Gb
NIC and and 2x10Gb NIC it was assumed that the server should have a
4x10Gb NIC before a 2x10Gb NIC according to slot order. New versions
of ASM allow more flexible NIC matching, i.e. in the previous example
a server that had a 2x10Gb NIC before a 4x10Gb NIC would also be
matched.
This commmit updates ASM::NetworkConfiguration to match NICs in a
similar fashion based on NIC capabilities. For each NIC requested in
the NetworkConfiguration a server NIC with matching capabilities (link
speed and number of NPAR partitions) will be found.
Link speed can be determined programatically via WS-Man in most
cases. However, if not available this code will fall back to …
> ASM-4621 choose best NICs to match NetworkConfiguration

- lib/asm/wsman.rb
In case NIC is having default current MAC Address then pick permanent MAC Address instead. This scenario is observed with Intel NICs
> Intel NIC having incorrect Current MAC Address

- .rubocop.yml
- .yardopts
- Rakefile
- dell-asm-util.gemspec
- lib/asm/wsman.rb
- spec/fixtures/wsman/connect_network_iso.xml
- spec/fixtures/wsman/fault.xml
- spec/fixtures/wsman/get_attach_status.xml
- spec/fixtures/wsman/osd_concrete_job.xml
- spec/fixtures/wsman/timed_out_fault.xml
- spec/unit/asm/wsman_spec.rb
- tasks/rubocop.rake
This PR is more preparation for supporting O/S installs via virtual media mount of ipxe.iso
- add support for DeploymentService ConnectNetworkISOImage, GetAttachStatus and GetNetworkISOConnectionInfo methods.
- add poll_for_lc_ready which will automatically disconnect ISO images. Those connections would block the LC from ever becoming ready. This is an improvement on wait_for_lc_ready.
- add parse method for parsing ws-man responses into ruby-like hashes. Also detects and parses ws-man fault responses.
- add snake_case and camel_case methods to make it easier to accept ws-man invoke command parameters as ruby-style hashes.
> ASM-5219 new ISO commands and better response parsing

- lib/asm/network_configuration.rb
- spec/unit/asm/network_configuration_spec.rb
Allow network configuration data to specify the exact NIC to use for
an interface rather than always picking it based on type and number of
partitions.
Additionally add the chosen NIC fqdd to the interface so
that the resulting data is consistent whether the network
configuration specified the NIC or it was chosen by add_nics!
> ASM-4621 use NICs in UI-specified order if available

- dell-asm-util.gemspec
- lib/asm/network_configuration.rb
- lib/asm/network_configuration/nic_port.rb
- lib/asm/network_configuration/nic_view.rb
- lib/asm/wsman.rb
- spec/unit/asm/network_configuration_spec.rb
- spec/unit/asm/wsman_spec.rb
- Add NicView data to the NetworkConfiguration partition data so that it is possible to determine what type of NIC is being used for e.g. the PXE partitions.
- Set boot order based on instance id rather than name. That makes it easy to set a specific NIC in the boot order based on its FQDD.
> ASM-5219 updates to support iPXE ISO boot

- lib/asm/wsman/parser.rb
The wrong value was being sent for power off.
> Fix WsMan#power_off

- lib/asm/network_configuration.rb
- lib/asm/network_configuration/nic_type.rb
- spec/unit/asm/network_configuration_spec.rb
Previously it was just returning the original network_configuration
data that was passed in from the UI. However that ignores the physical
NIC information that is captured when #add_nics! is called such as
FQDD and mac address. We would like to capture that data so that the
network configuration can be passed to razor ERB templates and used to
find out which NICs should be used for PXE boot.
> ASM-5141 capture NIC info in NetworkConfiguration#to_hash

- lib/asm/network_configuration.rb
- spec/unit/asm/network_configuration_spec.rb
Complex types were mistakenly being returned from #to_hash after
recent changes resulting in broken puppet yaml data in some cases.
> ASM-5660 strip out NicInfo in NetworkConfiguration#to_hash

- lib/asm/wsman.rb
- spec/unit/asm/wsman_spec.rb
The WS-Man command name was wrong. This method is not used by current
ASM workflows so it wasn't causing failures, but good to fix.
> misc: Fix get_network_iso_image_connection_info

- lib/asm/ipmi/client.rb
- lib/asm/wsman.rb
- lib/asm/wsman/client.rb
- spec/unit/asm/wsman_spec.rb
URI strings like nfs://hostname/path/to/boot.iso or
smb://hostname/path/to/boot.iso can now be used in the various ISO
connection methods rather than the rather cumbersome individual ws-man
parameters.
Also testing uncovered that ConnectRFSISOImage uses an inconsistent
parameter for username -- :username instead of :user_name. Update that
method to use :username
> ASM-5589 Allow using URI string to specify ISO boot location

- lib/asm/network_configuration/nic_view.rb
- spec/fixtures/network_configuration/fab_b_fab_c_nic_view.xml
- spec/unit/asm/network_configuration/nic_info_spec.rb
- spec/unit/asm/network_configuration/nic_view_spec.rb
The mezzanine fabric was not getting used in NicView comparisons or in
the generated card_prefix. This led to separate mezzanine cards,
e.g. 1B and 1C, appearing to be the same card and causing failures in
NicInfo.
> ASM-5815 Handle mezzanine card fabrics properly

- lib/asm/network_configuration/nic_port.rb
- spec/fixtures/network_configuration/x520_i350_nic_view.xml
- spec/unit/asm/network_configuration/nic_info_spec.rb
- spec/unit/asm/network_configuration/nic_port_spec.rb
Recognize the Intel X520/I350 combo card as a 2x10Gb,2x1Gb card even
in the case where LinkSpeed is not provided by the iDrac.
Now that ASM passes the chosen NIC FQDD as part of the
network_configuration data this is not strictly necessary, but it's
nice to keep this code in sync with the supported NICs.
> ASM-4774 Add special case for Intel X520/I350 combo card

- lib/asm/wsman.rb
Increasing LC status check timeout from 5 to 10 minutes to ensure we are waiting enough for server's LC status to be ready after reboot / power-on.
> ASM-6175 HyperV cluster configuration failed due to disable_pxe getting timed-out

- lib/asm/util.rb
Allow a timeout (in seconds) to be passed into the method
> ASM-6172 Allow timeout on #run_command_streaming

- lib/asm/wsman.rb
This is the default timeout period recommended by the LC team and it
seems like we are still seeing some cases where we time out waiting
for LC ready while disabling PXE boot.
> ASM-6223 Default to 30 minutes for LC ready timeout

- lib/asm/wsman/client.rb
- spec/unit/asm/wsman/client_spec.rb
Allow `:input_file` param to be passed into ASM::WsMan::Client#invoke
> ASM-6656 Wsman invoke input param

- dell-asm-util.gemspec
- lib/asm/wsman.rb
- lib/asm/wsman/parser.rb
- spec/unit/asm/wsman_spec.rb
As per new recommended flow and Virtual Media needs to be "Attached" state instead of default auto-attach state so that it will always show-up in the device list.
- Execute ConnectRFSISOImage to connect ISO
- Execute PowerStateChange to reboot the host
- Execute GetRemoteServicesAPIStatus, verify LCStatus is Ready
- Execute ChangeBootOrderByInstanceID to set virtual optical as first boot device
- Execute CreateTargetedConfigJob to set the boot order
- Verify config job completes
- Enum DCIM_BootSourceSetting to verify virtual optical is set as first boot device
- Verify system boots to RFS ISO
- Execute DisconnectRFSISOImage to disconnect RFS ISO
- Execute GetRemoteServicesAPIStatus, verify LCStatus is Ready
- Execute ImportSystemConfiguration
- Verify import job completes
- Execute …
> ASM-6387 ASM to support Urgent Fury vSAN RA

- lib/asm/wsman.rb
- spec/unit/asm/wsman_spec.rb
With the change to use Attach mode instead of Auto-Attach by default
(where the virtual CD is always listed in the boot order even if no
virtual CD is connected), it's possible that when boot_rfs_iso_image
is called the virtual CD is already first in the boot order. In that
case there was no need to change the boot order and the server did not
get rebooted into the newly attached ISO. In that case an explicit
reboot is now issued.
> ASM-6729 Ensure boot_rfs_iso_image reboots server

- lib/asm/wsman.rb
Recent changes were made to use "Attach" mode instead of "Auto Attach"
for the virtual CD. Attach mode makes the virtual CD remain in the
boot order even if not virtual ISO is attached. It's use is an
optimization as it should reduce the number of reboots required to
boot a virtual RFS ISO. These changes don't seem to be compatible with
idrac firmware version 1.57 as the name and values of the setting in
the idrac card enumeration have changed:
[2] pry(#<ASM::WsMan>)> idrac_card_enumeration.find { |e| e[:attribute_display_name] == "Attach Mode" }
=> {:attribute_display_name=>"Attach Mode",
:attribute_name=>"AttachMode",
:current_value=>"Auto Attach",
:default_value=>"Auto Attach",
:dependency=>nil,
:display_order=>"1232",
:fqdd=>"iDRAC.Embedded.1",
:group_display_name=>"Remote File …
> ASM-6806 Do not fail if missing Attach State

- lib/asm/wsman.rb
Update ws-man URLs to use "&" as query parameter separators; wsmancli
2.6 requires this. These URLs with work earlier wsmancli versions such
as 2. 3 as well.
> ASM-6558 Interoperability with wsmancli 2.6

- lib/asm/wsman.rb
- spec/fixtures/wsman/fc_view.xml
- spec/unit/asm/wsman_spec.rb
Added new helped method to retrieve WWPN and WWNN for the servers. This is required for EMC host authentications where tuple of WWPN and WWNN is required instead of just WWPN
> ASM-6515 ASM deployment to support EMC Storage provisioning for HyperV FC

- lib/asm/wsman.rb
- spec/unit/asm/wsman_spec.rb
For some servers, power-off operation is taking some time. Added validation loop to ensure server is powered-off when control is moved out of the method
> ASM-7035 VSAN deployment fails with VSAN partition on back side disk

- lib/asm/wsman.rb
- spec/unit/asm/wsman_spec.rb
The original code for setting attach mode was setting the incorrect
iDrac card enumeration enumeration attribute. This meant that the
server was always left in auto attach mode which requires an
additional reboot in order for the virtual CD to show up in the boot
order list after we attach the ISO. In attach mode the virtual CD is
always present in the boot order list even if no ISO is attached.
In addition to slowing down the install process the additional reboot
was occasionally causing servers to get rebooted while an OS
installation was already in progress and corrupting that install.
> ASM-7091 Use correct attribute for attach mode

- dell-asm-util.gemspec
Pins restclient to a version that works with our outdated ruby
>  misc: fix dependant builds

- lib/asm/network_configuration.rb
- spec/unit/asm/network_configuration_spec.rb
Generally boolean accessors should end with a question mark
> [maint] Rename has_fc to has_fc?

- lib/asm/util.rb
Some of msslq password keys are in the short form
of password ex: SApwd, adding pwd to the condition
such that pwd fields also replaced with *
> ASM-7739 Remove Mssql passwords as well from log

- lib/asm/wsman.rb
- lib/asm/wsman/client.rb
- spec/unit/asm/wsman/client_spec.rb
- spec/unit/asm/wsman_spec.rb
wsman identify command provides quick information about a server, and
can be used for scenarios like waiting on valid IDRAC server when IP
changes.
> ASM-7905 Utility method - wsman identify command

- dell-asm-util.gemspec
- lib/asm/firmware.rb
- lib/asm/transport/racadm.rb
- lib/asm/wsman.rb
- spec/unit/asm/firmware_spec.rb
- spec/unit/asm/wsman_spec.rb
migrating firmware update IDRAC module to Util. through which we  can remove possible unnecessary XML config files in IDRAC module , By using only existing wsman commands. 
cautions: 
Had to include "net/ssh" library to Gem file.
> ASM-7884 migrating firmware update utility from Idrac module to util

- dell-asm-util.gemspec
The ASM appliance ships with net-ssh 2.9.4 currently, so updating the
net-ssh gemspec dependency to be compatible with that.
> ASM-8201 Update net-ssh dependency

- lib/asm/firmware.rb
- lib/asm/wsman.rb
- spec/unit/asm/firmware_spec.rb
Fix the firmware update code that was incorrectly ported over from
the idrac puppet module.  This was resulting in the reboot
job and the job queue never being scheduled.
Also, we were incorrectly finishing the job early without checking
all of the statuses
> ASM-7884, ASM-8182 Firmware updates failing

- lib/asm/network_configuration.rb
- spec/unit/asm/network_configuration_spec.rb
Previously we reject pxe network from the vim_nic to add to specific ports
This PR will adds pxe and configure port_group with pxe on configured nic.
> ASM-8191: Adds PXE to specified matching Nic in standard switch of cluster

- lib/asm/transport/racadm.rb
Idrac reset is failing because the ssh connection was expecting
the user to enter a password because we were currently supplying
null for the value
> ASM-8336 Idrac Reset failing

- dell-asm-util.gemspec
- lib/asm/wsman.rb
- lib/asm/wsman/parser.rb
- spec/unit/asm/wsman_spec.rb
In general it's better to do graceful shutdowns than just shutting off
power. There is no straightforward WS-Man method to implement
"graceful with forced" shutdown functionality -- i.e. issuing a
graceful shutdown and then switching off the power at some point if
the OS doesn't respond. This change makes the default
`wsman.power_off` call execute in this manner.
This specifically addresses some cases that were seen when resetting
ESXi management IPs where that command seems to succeed but after
force powering off the server (the previous functionality of
`wsman.power_off`) and then powering it back on that configuration
change was lost.
> ASM-8733 Do graceful power offs by default

- .travis.yml
- dell-asm-util.gemspec
- lib/asm/util.rb
- The timeout command argument was passed as a Fixnum argument to
Open3.popen3 which fails with "TypeError: no implicit conversion of
Fixnum into String". Interestingly that fails under ruby 1.9 as
well, it only seems to work in jruby 1.7
- Pin rainbow to 2.0.x to work around issues with [bundler 0.14 and
rainbow][1].
[1]: https://github.com/sickill/rainbow/issues/48
> ASM-8652 Fixes for jruby 9

- lib/asm/wsman/client.rb
- spec/unit/asm/wsman/client_spec.rb
Previously WsMan::Client accepted a hash of options but ignored these
options and used hard coded defaults instead
Now it uses these options to influence the defaults thus retaining the
ability to make specific per exec adjustments but allowing for different
defaults that would affect all other methods
> ASM-9191 let wsman client options adjust exec behaviour

- lib/asm/wsman.rb
Previously reboot job has 5 minutes to timeout, sometimes resulting
in timeout  error  waiting for LC ready if servers takes more than 5 minutes.
This PR increases the time to 15 minutes to wait for LC to become ready.
> ASM-9333 Increased time-out for reboot job event from 5 to 15 mnts

- lib/asm/util.rb
`ASM::Util.run_command_simple` just executed a string command through
bash. Its usage is prone to command injection attacks since callers
frequently forget to escape unsafe input. And even if they try it's
nigh impossible to guarantee everything dangerous has been stripped
out.
The current pattern we promote is to use
`ASM::Util.run_command_with_args` instead. It executes a command with a
list of arguments. The command itself is not executed through bash so
command injection becomes much more difficult.
> ASM-9078 Remove ASM::Util.run_command_simple

- .travis.yml
- dell-asm-util.gemspec
- spec/spec_helper.rb
- spec/unit/asm/network_configuration/nic_type_spec.rb
- spec/unit/asm/network_configuration_spec.rb
Open up most library version requirements in gemspec. This makes it
easier for the consuming application to specify the versions they
require. This is at the expense of making it more likely that
dell-asm-util tests will fail at some point as new library versions
are released.
Rubocop was left at version 0.37.2 because upgrading that will require
updating code style to match and not fail the new rubocop
checks. Puppetlabs_spec_helper was left at 0.4.1 for now as otherwise
rake task fail.
Travis CI was updated to test against jruby 1.7, jruby 9 and ruby
2.4.3 which are the primary targets now
> ESTS-140275 Allow latest versions of gems in gemspec

- lib/asm/network_configuration.rb
- lib/asm/network_configuration/nic_info.rb
- lib/asm/network_configuration/nic_port.rb
- lib/asm/network_configuration/nic_type.rb
- lib/asm/network_configuration/nic_view.rb
- spec/fixtures/network_configuration/mellanox_connect_x_4_lx_nic_view.xml
- spec/fixtures/network_configuration/x710_i350_nic_view.xml
- spec/unit/asm/network_configuration/nic_info_spec.rb
- spec/unit/asm/network_configuration/nic_port_spec.rb
- spec/unit/asm/network_configuration/nic_type_spec.rb
Additionally added some specific checks for Intel X710 which was
already supported. Both the X520 and X710 have both 2x10Gb and 4x10Gb
variants but the previous X520 check was specific to 2-port.
> LUD-279 Add support for Mellanox 25Gb NICs

- lib/asm/firmware.rb
For the service firmware update task, poll_for_lc_ready breaks often
by the endpoint being in a reboot stage.
Now it handles exception caused by API calls failing to reach iDRAC
servers.
> LUD-421b poll_for_lc_ready to handle API errors

- lib/asm/wsman.rb
- lib/asm/wsman/parser.rb
- spec/unit/asm/wsman_spec.rb
In addition to putting server and its related components into
maintenance mode, this change is required to set the LED blinker
state through IdentifyChassis method using wsman.
> LUD-959 enable/disable iDRAC front panel LED light

- lib/asm/firmware.rb
- spec/unit/asm/firmware_spec.rb
It looks like we don't wait for the LC status to be ready when we
perform the firmware update job for the  LC. This causes issue for
the next non-LC firmware updates.
> LUD-1187 always wait and rescue timeout after firmware update

- lib/asm/network_configuration/nic_port.rb
- spec/unit/asm/network_configuration/nic_port_spec.rb
Seeing various issues on iPXE ISO boot so disabling:
- ISO doesn't see port 2 on Intel X710 NICs
- Mellanox ConnectX-4 LX OS install times very slow
> LUD-1437,LUD-1455 Disable iPXE ISO usage

- lib/asm/firmware.rb
There are few occasions where FW/SW update job fails, due to iDRAC
jobs that are stuck in the queue. To mitigate this type of failures,
we now attempt to force clear the iDRAC job queue if the first
try fails.
> LUD-1453 force to clear iDRAC job queue

- lib/asm/util.rb
- spec/unit/asm/util_spec.rb
Environment was causing errors to occur in some cases when ansible
inventory was run outside of a script.
> VXFM-4040 Update ansible inventory calls to run with a clean environment

- lib/asm/util.rb
- spec/unit/asm/util_spec.rb
Provide method to remove host file entry which can be called before
ansible run.
> VXFM-5171 Inventory fails as host key checking seems to still occur on Ansible inventories.

- lib/asm/network_configuration.rb
NIC Team information is getting cached. During VDS and Distributed PG configuration PXE network information was missing from the NIC team response, Now we have included a option to refresh the information as when required.
> VXFM-7884 PXE Distributed port-group is not created after VDS refactoring changes

- lib/asm/util.rb
- spec/unit/asm/util_spec.rb
Constant Net::SSH::Verifiers::Null is available in the latest Net::SSH version leading to the falure. Replaced this with false which is the valid equivalent of the constant in the current release.
>  VXFM-8972 High chance linux CO nodes will fail first time and require retry

- lib/asm/firmware.rb
- lib/asm/util.rb
- lib/asm/wsman.rb
- spec/unit/asm/firmware_spec.rb
- spec/unit/asm/util_spec.rb
Seeing cases where force clearing the job queue failed which appear to
be caused by issuing the command when LC is not ready.
> VXFM-9100 Add wait for LC ready before clearing job queue

- lib/asm/transport/racadm.rb
- lib/asm/util.rb
- lib/asm/wsman.rb
- spec/unit/asm/util_spec.rb
`Net::SSH::Verifiers::Null` was removed. It looks like
`:verify_host_key => :never` is the more correct way to disable host
key verification but for Dacite release sticking with
`:verify_host_key => false` which is already in use in existing code.
> VXFM-9100 Automated iDrac reset was failing due to Net::SSH changes

- lib/asm/util.rb
- spec/unit/asm/util_spec.rb
Due to recent refactoring of dell-asm-util for ESXCLI parsing, few columns were not getting parsed correctly leading to the failure in identifying the VMNICS. Updated the paring logic to ensure we collect all the headers and respective information
> VXFM-9282 ESXCLI VMNIC parsing failing

- lib/asm/util.rb
- spec/unit/asm/util_spec.rb
If exeception is encounted in threaded operation then need to include the information in the returned information so that calling method can take corrective action
> VXFM-9700 Record exception in the thread

- lib/asm/util.rb
- spec/unit/asm/util_spec.rb
Currently, ssh session will prompt for a correct password if VXFM uses incorrect password during session initiation and eventually raises ioctl error.
This PR adds non-interactive option making session non-interactive and fails with authentication error when an incorrect password is used.
> VXFM-9677 Fixed ioctl error for ssh authentication issue
