lib/asm/network_configuration.rb, spec/unit/asm/network_configuration_spec.rb
Added helper method to collect nic team information based on the networks selected on each of the partitions
=> ASM-2062 Support Post OS NIC configurations for Windows

lib/asm/wsman.rb
DO NOT MERGE: Still testing.
@gavin-scott I don't know if we ever plan on using this for any other kind of ISO other than the small one, so the hour long timeout I have right now might be WAY overkill.
Just review and let me know if there's anything you want to change here, including that.
=> Added support for attach/boot network iso

Gemfile, Rakefile, dell-asm-util.gemspec, lib/asm/errors.rb, lib/asm/network_configuration.rb, lib/asm/network_configuration/nic_info.rb, lib/asm/network_configuration/nic_port.rb, lib/asm/network_configuration/nic_view.rb, lib/asm/translatable.rb, lib/asm/util.rb, lib/asm/wsman.rb, spec/spec_helper.rb, spec/unit/asm/network_configuration/nic_info_spec.rb, spec/unit/asm/network_configuration/nic_port_spec.rb, spec/unit/asm/network_configuration/nic_type_spec.rb, spec/unit/asm/network_configuration_spec.rb, spec/unit/asm/util_spec.rb, spec/unit/asm/wsman_spec.rb, tasks/rubocop.rake
Correct all rubocop offenses and enable it to run with the default rake task.
=> maint: correct rubocop style offenses

lib/asm/ipmi.rb, lib/asm/ipmi/client.rb, spec/unit/asm/ipmi/client_spec.rb, spec/unit/asm/ipmi_spec.rb
Implement common operations power_state, reboot, power_on and power_off using the ipmitool client.
=> Implement IPMI client similar to WsMan client

lib/asm/network_configuration.rb, lib/asm/wsman.rb, lib/asm/wsman/parser.rb, spec/unit/asm/wsman_spec.rb
- Pass :reboot_job_type through from boot_rfs_iso_image to set_boot_order
- Remove unused NetworkConfiguration#is_blade?
- Implement WsMan #power_on and #power_off as instance methods
- Return :on or :off from #power_state rather than a string
=> Various fixes and enhancements

bin/wsman_shell.rb, dell-asm-util.gemspec
Executable allows for simple execution of wsman commands.
=> Add wsman_shell executable to gem

lib/asm/network_configuration/nic_port.rb, lib/asm/wsman.rb, lib/asm/wsman/parser.rb, spec/unit/asm/wsman_spec.rb
- Add various firmware and raid-related inventory ws-man calls. Not used anywhere, but useful for debugging with wsman_shell.rb
- Fix for style changes in rubocop 0.37
=> misc: Additional ws-man enumerations and style updates

lib/asm/wsman.rb
@gavin-scott Please help review and merge
=> Branch merge 820 to master 28 for dell-asm-util

dell-asm-util.gemspec, lib/asm/util.rb
@gavin-scott review and merge? Thanks.
=> Branch merge 820 to master dell asm util 73

lib/asm/wsman/client.rb, spec/unit/asm/wsman/client_spec.rb
@gavin-scott Please review and merge. Thanks.
=> Branch merge 820 to master dell asm util 78

lib/asm/wsman.rb, spec/unit/asm/wsman_spec.rb
Recent changes were made to the boot_rfs_iso_image workflow in
response to problems that were seen where ImportSystemConfiguration or
CreateTargetedConfig jobs became stuck in running state. LC team has
now root caused this and the problem was arising when an
ImportSystemConfiguration job was run that set BiosBootSeq or HddSeq
but the applied configuration did not result in any actual
configuration changes. In that case subsequent jobs would become stuck
in Running state.
In response to the root cause analysis this commit adds back some
things that were removed previously:
- Revert back to using CreateRebootJob in boot_rfs_iso_image as that
was not a source of problems.
- Only reboot the server after connecting the RFS ISO image if the
virtual CD is not already detected. In Attach mode …
=> ASM-6387 Boot RFS ISO image workflow tweaks

lib/asm/wsman.rb, lib/asm/wsman/parser.rb, spec/unit/asm/wsman_spec.rb
@gavin-scott looks like this is newly changes on 8.2.1. See if you want to merge to 8.3
=> Branch merge 820 to master dell asm util 101

dell-asm-util.gemspec, lib/asm/racadm.rb, lib/asm/racadm/transport.rb, lib/asm/util.rb, lib/asm/wsman.rb, lib/asm/wsman/client.rb, lib/asm/wsman/response_error.rb
Reset the iDRAC when a wsman call returns non-UTF-8 encoding
=> ASM-7468 Rescue non-UTF-8 wsman response

lib/asm/wsman/client.rb, spec/unit/asm/wsman/client_spec.rb
=> ASM-7468-2 Fix typo in UTF8Error raising

lib/asm/wsman/client.rb, spec/unit/asm/wsman/client_spec.rb
Reverts dell-asm/dell-asm-util#69
=> Revert "ASM-7468-2 Fix typo in UTF8Error raising"

.gitignore, .travis.yml, dell-asm-util.gemspec, spec/spec_helper.rb, spec/unit/asm/firmware_spec.rb, spec/unit/asm/network_configuration/nic_info_spec.rb, spec/unit/asm/network_configuration/nic_port_spec.rb, spec/unit/asm/network_configuration/nic_view_spec.rb, spec/unit/asm/network_configuration_spec.rb, spec/unit/asm/util_spec.rb, spec/unit/asm/wsman_spec.rb
Also update rspec to latest and updates the rspec syntax
=> misc: modern ruby and coveralls integration

lib/asm/firmware.rb
Using StringF notation we need to make sure the argument is a string
=> ASM-9359 FW Update Debug line throwing "too few args"

lib/asm/util.rb, spec/unit/asm/util_spec.rb
Since ESXi 6.7 requires CA cert installation or thumbprint validation,
lib/asm/util.rb file was updated to meet this requirement.
For the purpose of this task, temporary thumbprint validation seemed
as the most appropriate solution, as this method does not require
clean up during the teardown.
A helper method was implemented to grab and parse the thumbprint,
and it is called from the esxcli method to set a command argument.
=> ESTS-139864 support ESXi 6.7 deployment

lib/asm/util.rb, spec/unit/asm/util_spec.rb
The vmware module uses this method to determine the local IP to use as
an NFS mount. In cases where the ESXi hosts are added to the vcenter
via their hostname rather than IP this was failing.
=> Accept hostname in `ASM::Util.get_preferred_ip`

lib/asm/firmware.rb
After the last commit, with changes that wraps polling for LC
status for the firmware update, it was discovered by QAs that
timeout exceptions still can be caused by clear_job_queue_retry
method. This change wraps the call to WsMan::poll_for_lc_ready in
clear_job_queue_retry method to prevent the issue.
=> LUD-1187b handle timeout issue with LC status check

lib/asm/wsman/client.rb, spec/unit/asm/wsman/client_spec.rb
Reverts dell-asm/dell-asm-util#113
=> Revert "VXFM-2511 [Security] Replace URI.escape with CGI::escape"

lib/asm/util.rb, spec/unit/asm/util_spec.rb
Updated util to include method for executing a script via SSH.
=> VXFM-2097 Be able to input the root creds for FlexOS gateway during discovery.

lib/asm/util.rb
Fix for more flexibilty on inputs of arguments.
=> VXFM-2097 Be able to input the root creds for FlexOS gateway during discovery

lib/asm/util.rb, spec/fixtures/testdevice.out, spec/fixtures/testdevice2.out, spec/fixtures/write_ansible.yaml, spec/unit/asm/util_spec.rb
Added methods to get vault encrypted values, write ansible playbooks and
inventory files from hash, run ansible, and process an text output
file with ansible result.
=> VXFM-4200 Develop the foundation code to enable run Ansible playbook

lib/asm/wsman.rb, spec/unit/asm/wsman_spec.rb
Adds support for setting UEFi boot orders and for virtual floppy
images.
=> VXFM-5086 Support UEFi virtual media boot

lib/asm/wsman.rb, spec/unit/asm/wsman_spec.rb
Including WSMAN interface for fetching memory view and identify availability of NVDIMMs on server
=> VXFM-5851 Need to sanitize NVDIMMs during new deployment

lib/asm/wsman.rb, spec/unit/asm/wsman_spec.rb
Changed find_boot_device to look for pattern
=> VXFM-6275 UEFI PXE fails to find BOSS in boot list

spec/unit/asm/wsman/parser_spec.rb
Some existing styling violations in dell-asm-util modules
=> Rubocop styling violations

lib/asm/util.rb, spec/unit/asm/util_spec.rb
Make it more clear when and why thumbprint retrieval fails.
=> VXFM-8106 Added logging around thumbprint retrieval failure

lib/asm/wsman.rb, spec/unit/asm/wsman_spec.rb
For UEFi boot the OS may show up as the default boot option without
having to change the boot order. This changes adds a flag
`:always_reboot` to allow the caller to ensure that a reboot always
occurs, e.g. to ensure that kernel updates are applied.
=> VXFM-8298 Add set_boot_order option to always reboot

lib/asm/util.rb, spec/unit/asm/util_spec.rb
dell-force10 needed a more robust way of parsing LLDP neighbors output
for cases where there were no spaces between columns on some rows.
=> VXFM-9193 Create reusable table parsing method

lib/asm/util.rb
Previous implementation was taking 5-10 minutes when the ansible log
was about 13MB. New implementation is around 10 seconds.
=> VXFM-9305 Improve performance of parse_ansible_log
